services:
  - id: svc01
    envRef: env01
    sinkRef: agent1
    finalWork: work01
    units:
      - work: work02
        svc: svc02
      - svc: svc03
    context:
      tags:
        - keyLength: 20
          valueLength: 40
        - keyStatic: method
          valueLength: 60
      baggage:
        - keyLength: 10
          valueLength: 30
  - id: svc02
    envRef: env02
    sinkRef: agent2
    units:
      - work: work02
        svc: svc04
    context:
      tags:
        - keyStatic: idString 
          valueStatic: authN
  - id: svc03
    envRef: env03
    sinkRef: agent3
    units:
      - work: work01
    context:
      tags:
        - keyLength: 25
  - id: svc04
    envRef: env03
    sinkRef: agent3
    units:
      - work: work02
sinks:
  - id: agent1
    type: provided
    hostport: localhost:6831
    envRef: env01
  - id: agent2
    type: provided
    envRef: env02
  - id: agent3
    envRef: env03
    type: provided
workUnits:
  - id: work01
    type: constant
    params:
      value: 100
  - id: work02
    type: gaussian
    params:
      mean: 50
      stddev: 20