version: '3'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: ["/go/bin/collector-linux", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
      networks: 
        - tracer-backend
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "9411:9411"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["/go/bin/query-linux", "--query.static-files=/go/jaeger-ui/", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      networks: 
        - tracer-backend
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      depends_on:
        - cassandra-schema

    cassandra:
      image: cassandra:3.9
      networks: 
        - tracer-backend

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      networks: 
        - tracer-backend
      depends_on:
        - cassandra
networks:
  tracer-backend: