# Global prometheus config to scrape from local jaeger backend; based on https://github.com/prometheus/prometheus/blob/release-2.7/config/testdata/conf.good.yml
global:
  scrape_interval:     5s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

scrape_configs:
- job_name: 'node-exporter'
  static_configs:
  - targets: ['node-exporter:9100']
- job_name: cadvisor
   # static configs for cadvisor metrics
  static_configs:
  - targets: ['cadvisor:8080']
- job_name: jaeger
  honor_labels: true
   # static configs for jaeger agent and collector; query also possible: 'jaeger-query:16686'
  static_configs:
  - targets: ['jaeger-agent:5778', 'jaeger-collector:14268']
- job_name: workers
  honor_labels: true
  # static configs for up to 4 workers running locally on a docker host!
  static_configs:
  - targets: ['172.31.16.225:9000', '172.31.24.229:9000']