kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-https-cfg
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    insecureSkipVerify = true
    #rootCAs = [ "./backend/tls.crt" ]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
        # For secure connection on frontend.local
          [[entryPoints.https.tls.certificates]]
          certFile = "/frontend/tls.crt"
          keyFile  = "/frontend/tls.key"

    [api]

    [file]

    [backends]
      [backends.backend1]
        [backends.backend1.servers.server1]
        # Access on backend with HTTPS
        url = "https://backend.local:7878"


    [frontends]
      [frontends.frontend1]
      backend = "backend1"
        [frontends.frontend1.routes.test_1]
        rule = "Host:frontend.local"